//
//  Problem2.swift
//  ProjectEuler-Swift
//
//  Created by CruzDiary on 10/10/2016.
//  Copyright © 2016 swiftycruz. All rights reserved.
//
//  Even Fibonacci numbers
//
//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


import Foundation

class Problem2: Problem {
    func answer(input: Int) -> Int {
        //below input
        var value: (Int, Int) = (1, 2)
        var sum: Int = 0
        while (value.1 < input) {
            if value.1 % 2 == 0 {
                sum += value.1
            }
            value = next(value: value)
        }
        return sum
    }
    
    func next(value:(Int, Int)) -> (Int, Int) {
        return (value.1, value.0 + value.1)
    }
}
